### ISSUE TITLE
bug: incorrect value after toggle

### ISSUE THREAD

**Issue by Scrum** [braintree/restricted-input#58]
### General information

* Library version: 2.0.0
* Browser and OS: Chrome,Firefox,Safari (latest) on MacOS 10.14.5

### Issue description
Bug can look at https://braintree.github.io/restricted-input/

### Steps
1. I enter the value (4111111111111111) in field `Card Number (toggle-able)`
2. I press the button `toggle` twice
3. and get the formatted value one less character `4111 1111 1111 111`

**Comment by crookedneighbor** [comment]
This is expected, as the pattern it toggles to has 15 characters instead of 16 characters. When the input starts at 16 characters and then is restricted to 15 characters, it makes sense that the final character would be cut off when toggled back.

This particular example is emulating a toggle between a non-American Express card (which usually has 16 digits) and an American Express card (which only has 15 digits).

**Comment by Scrum** [comment]
Your truth, but I noticed another mistake while trying to understand the reasons for this behavior. this can be seen on my [demo page](https://scrum.github.io/credit-card-gaps-pattern/) There you may notice that I obviously change the value of the element

```js
function setUnionpay() {
  element.value = data.unionpay.value;
  formattedCreditCardInput.setPattern(creditCardGapsPattern(data.unionpay.gaps, data.unionpay.lengths));
}

function setAmex() {
  element.value = data.amex.value;
  formattedCreditCardInput.setPattern(creditCardGapsPattern(data.amex.gaps, data.amex.lengths));
}
```

then the unformat method does not take into account the characters used in the pattern.

I created a [PR](#59 ) where there is a playback test

**Comment by Scrum** [comment]
@crookedneighbor tagging you just in case you don’t see this, otherwise.
